apiVersion: v1
kind: Service
metadata:
  name: pingaccess
  labels:
    app: pingaccess
spec:
  ports:
    - port: 9000
      name: pa-admin
    - port: 443
      name: pa-app
  selector:
    app: pingaccess
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingaccess
  labels:
    app: pingaccess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingaccess
  template:
    metadata:
      name: pingaccess
      labels:
        app: pingaccess
    spec:
      containers:
        - name: pingaccess
          image: pingidentity/pingaccess:edge
          ports:
            - containerPort: 9000
            - containerPort: 443
          env:
            - name: SERVER_PROFILE_URL
              value: "https://github.com/gmorgan-ping/ping-baseline.git"
            - name: SERVER_PROFILE_PATH
              value: "baseline/pingaccess"

